### ISSUE TITLE
Flutter/Flutter/Flutter.h not found

### ISSUE THREAD

**Issue by a-voyager** [alibaba-flutter/hybrid_stack_manager#3]
![image](https://user-images.githubusercontent.com/12423772/50686256-8e78ee80-1057-11e9-9697-dda9770cda3e.png)

![image](https://user-images.githubusercontent.com/12423772/50686295-b9634280-1057-11e9-8e05-02900babcdd4.png)

Compile failed

**Comment by a-voyager** [comment]
It's cocoapods's bug, I resolved it by replace the Pods file

**Comment by jiangmingz** [comment]
> It's cocoapods's bug, I resolved it by replace the Pods file

怎么替换的，我删除pods重新pod install一样的错误

**Comment by jiangmingz** [comment]
@a-voyager 怎么替换的，我删除pods重新pod install一样的错误

**Comment by a-voyager** [comment]
把 ios 目录下的 Podfile 文件替换掉（两个文件选一个，一个是 OC 项目用，另一个是 Swift 项目用的），重新编译就好了
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods

**Comment by kangwang1988** [comment]
抱歉，之前因为我没能复现，所以没改。刚看了下，是因为podspec的问题，我这边复现也修改了，可以试下0.1.1

**Comment by kangwang1988** [comment]
0.1.1应该已经修复这个问题。

**Comment by a-voyager** [comment]
@kangwang1988 感谢！已验证没问题了。
